import { PLAN_PRICE_LABEL, TRIAL_DAYS } from "../plan-constants";

export type KnowledgeDocument = { id: string; title: string; tags: string[]; routes: string[]; content: string };
// Versioned product knowledge. These answers describe controls verified in the repository;
// they do not infer a provider's balance, subscription, budgets or account state.
export const knowledge: KnowledgeDocument[] = [
  { id: "criar-orcamento", title: "Criar orçamento", tags: ["criar orçamento", "novo orçamento", "fazer orçamento", "montar orçamento"], routes: ["/painel/orcamentos/novo", "/painel/orcamentos"], content: "Abra Orçamentos e toque em Novo orçamento. Escolha um cliente ou cadastre nome e telefone no formulário. Adicione os serviços, quantidades e valores, revise prazo, validade e condições de pagamento. Use Salvar rascunho para guardar ou Salvar e enviar para compartilhar. Serviços já cadastrados podem ser usados no orçamento." },
  { id: "editar-orcamento", title: "Editar orçamento", tags: ["editar orçamento", "mudar orçamento", "corrigir orçamento", "alterar orçamento", "edição"], routes: ["/painel/orcamentos"], content: "Abra Orçamentos, selecione o orçamento e toque em Editar. Ajuste os itens, valores, prazo ou condições e salve as alterações. Se o cliente pediu alteração, revise o pedido e use Mandar a alteração para avisá-lo. O link continua o mesmo. Consulte o status exibido no orçamento; não consigo afirmar o status de um orçamento específico por esta orientação." },
  { id: "aprovacao", title: "Aprovação e recusa", tags: ["aprovar", "aprovação", "cliente aprova", "recusar", "recusa", "aceitar"], routes: ["/painel/orcamentos"], content: "O cliente abre o link do orçamento no celular, sem instalar aplicativo. Na proposta, pode Aprovar, Recusar ou escolher Quero alterar. A resposta atualiza o status no painel do prestador. Para verificar uma proposta específica, abra o orçamento no painel." },
  { id: "pedido-alteracao", title: "Pedido de alteração", tags: ["pedido de alteração", "pedir alteração", "quero alterar", "cliente pediu", "revisão"], routes: ["/painel/orcamentos"], content: "No link público, o cliente pode tocar em Quero alterar e escrever o ajuste desejado. O pedido aparece no orçamento no painel. Abra o orçamento, leia a solicitação, edite e salve. Depois toque em Mandar a alteração para avisar o cliente; a proposta usa o mesmo link e ele pode analisar novamente." },
  { id: "servicos", title: "Adicionar serviço", tags: ["adicionar serviço", "cadastrar serviço", "novo serviço", "criar serviço", "preço do serviço", "serviços"], routes: ["/painel/servicos", "/painel/pagina"], content: "Abra Serviços e toque em Novo serviço, ou use Adicionar serviço na edição da sua página. Preencha nome, descrição, unidade e preço de referência; uma foto ajuda a mostrar o trabalho. Salve o serviço. Serviços ativos aparecem na página e podem ser selecionados ao montar um orçamento. A opção Mostrar preço controla a exibição do preço na página." },
  { id: "destaques", title: "Serviços destacados", tags: ["destaque", "destacar", "destacados", "aparecer primeiro", "ordem dos serviços"], routes: ["/painel/servicos", "/painel/pagina"], content: "Abra o serviço para editar e ative Serviço em destaque. Salve as alterações: os destaques aparecem primeiro na página profissional. Você pode desativar a opção a qualquer momento. Use fotos e nomes claros para ajudar o cliente a entender o serviço." },
  { id: "pagina", title: "Configurar página profissional", tags: ["configurar página", "minha página", "página profissional", "página comercial", "editar página", "página bonita"], routes: ["/painel/pagina"], content: "Abra Página no painel. Ali você pode editar a identidade visual, descrição, contatos, cidade e área de atendimento, serviços e fotos dos trabalhos. Use os controles de edição de cada seção e salve. O link público permite ver como a página aparece para o cliente." },
  { id: "logo", title: "Logo da empresa", tags: ["logo", "logotipo", "marca"], routes: ["/painel/pagina"], content: "Em Página, abra a edição da identidade da empresa para enviar ou trocar o logo. Selecione a imagem, ajuste o recorte e salve. O logo identifica sua empresa na página profissional. Use uma imagem legível e confira o resultado no link público." },
  { id: "capa", title: "Capa da página", tags: ["capa", "imagem de fundo", "banner"], routes: ["/painel/pagina"], content: "Em Página, use o controle de edição da capa. Escolha uma imagem e ajuste o enquadramento antes de salvar. A capa é o fundo do cabeçalho da página profissional; confira o resultado no celular e no link público. Ela é diferente do logo e da foto de um serviço." },
  { id: "fotos", title: "Fotos dos trabalhos", tags: ["foto", "fotos", "galeria", "imagem", "portfólio"], routes: ["/painel/pagina"], content: "Abra Página e vá até as fotos dos trabalhos. Toque em Adicionar fotos, selecione uma imagem e, se desejar, informe um título. A galeria permite até 12 fotos; remova uma antiga para adicionar outra quando atingir o limite. A foto de um serviço é editada no próprio serviço." },
  { id: "cidades", title: "Cidade da empresa", tags: ["cidade", "cidades", "município", "localização", "endereço"], routes: ["/painel/pagina"], content: "Na edição de Página, abra as informações da empresa. Busque e selecione sua cidade na lista e salve. Use uma cidade válida selecionada no campo, não apenas um texto digitado. A cidade ajuda clientes a encontrar prestadores na busca." },
  { id: "area-atendimento", title: "Área de atendimento", tags: ["área de atendimento", "atendimento regional", "cidades atendidas", "raio", "região", "atender cidade"], routes: ["/painel/pagina"], content: "Em Página, nas informações da empresa, configure a cidade e a área de atendimento. Indique explicitamente as outras cidades que atende e salve. A busca considera as cidades atendidas; selecionar um estado não significa atender automaticamente todos os municípios dele. Revise a lista para refletir onde você realmente trabalha." },
  { id: "compartilhar", title: "Compartilhar página e orçamento", tags: ["compartilhar", "link", "enviar", "mandar", "whatsapp", "instagram"], routes: ["/painel/pagina", "/painel/orcamentos"], content: "Para divulgar a empresa, abra Página e use as opções de compartilhar ou copiar o link público. Você pode colocá-lo na bio do Instagram e no status do WhatsApp. Para uma proposta, abra o orçamento e toque em Mandar no WhatsApp. Se a janela não abrir, copie a mensagem ou o link e envie manualmente." },
  { id: "plano", title: "Plano e período de teste", tags: ["plano", "trial", "teste grátis", "assinatura", "preço", "quanto custa", "mensalidade", "pagamento"], routes: ["/painel/plano", "/painel/conta"], content: `O plano padrão do ORÇAH oferece ${TRIAL_DAYS} dias grátis para testar e depois ${PLAN_PRICE_LABEL}, com orçamentos ilimitados. Abra Plano para consultar o status, prazo e opções de ativação da sua própria conta. Algumas contas internas podem ter condições diferentes. Esta orientação não confirma pagamento nem validade do seu plano.` },
  { id: "busca", title: "Buscar prestadores", tags: ["busca de prestadores", "buscar prestador", "encontrar prestador", "aparecer na busca", "pesquisar prestador"], routes: ["/painel/pagina"], content: "A busca pública de prestadores permite procurar por serviço e cidade. Para ajudar clientes a encontrar sua empresa, mantenha serviços ativos, cidade e cidades atendidas corretos na página. A busca não considera todo o estado como área atendida. Não posso prometer posição ou quantidade de resultados para uma empresa específica." },
  { id: "configuracoes", title: "Configurações do painel", tags: ["configurações", "configurar painel", "conta", "senha", "dados de acesso", "sair"], routes: ["/painel/conta", "/painel/mais"], content: "Em Conta ficam os dados de acesso e opções da conta. O visual, as fotos e os contatos públicos da empresa ficam em Página. Em Mais você encontra atalhos para plano, página pública e saída da conta. Nunca envie sua senha, documento ou códigos de acesso no chat. Para dificuldade de acesso, use os recursos de recuperação da tela de login ou peça atendimento humano." },
  { id: "pedidos", title: "Pedidos da página", tags: ["pedido de orçamento", "pedidos", "cliente pediu orçamento", "converter pedido"], routes: ["/painel/pedidos"], content: "Pedidos são solicitações de clientes pela sua página profissional. Abra Pedidos e toque em Criar orçamento na solicitação. Os dados do cliente e do serviço vêm preenchidos para você revisar antes de enviar a proposta. Consulte a lista no painel para saber quais pedidos sua empresa recebeu." },
];
