import type { BudgetFormLayout, CatalogItem, ExtraField, TemplateConfig } from "@/lib/templates";

export type RamoMolde = {
  title?: string;
  publicTitle?: string;
  newLabel?: string;
  units: string[];
  defaultUnit: string;
  extras: ExtraField[];
  suggestions: CatalogItem[];
  photos?: TemplateConfig["photos"];
  groupLabel?: string;
  groupPlaceholder?: string;
  groupSuggestions?: string[];
  groupSectionTitle?: string;
  form: BudgetFormLayout;
};

function simple(overrides: Partial<BudgetFormLayout> = {}): BudgetFormLayout {
  return {
    simplified: true,
    extraTitle: undefined,
    showAddress: false,
    showStateCity: false,
    showValidity: true,
    showPrazo: true,
    validityInSummary: true,
    itemLayout: "standard",
    itemNotes: true,
    itemMaterial: false,
    itemDeadline: false,
    itemPhotoHint: false,
    itemMeasures: false,
    itemAreaNote: false,
    itemAreaM2: false,
    itemPowerKwp: false,
    itemVolumeM3: false,
    itemSizeWH: false,
    itemSizeLW: false,
    itemSizeWHD: false,
    addressRequired: false,
    showTravelFee: false,
    hideKinds: true,
    hideGroups: true,
    hideItemDiscount: true,
    catalogSave: true,
    ...overrides,
  };
}

const photosOptional: TemplateConfig["photos"] = {
  enabled: true,
  placement: "after-items",
  sectionTitle: "Fotos",
  hint: "Opcional — anexa depois de salvar.",
  captionRequired: false,
};

export const ramoMoldes: Record<string, RamoMolde> = {
  agencia: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    newLabel: "Novo orçamento",
    units: ["un", "serviço", "h", "pacote"],
    defaultUnit: "un",
    extras: [],
    suggestions: [],
    photos: photosOptional,
    form: simple(),
  },
  antenista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação de antena", unit: "serviço" },
      { name: "Ajuste de antena", unit: "serviço" },
      { name: "Troca de antena", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Opcional — foto da instalação ou do equipamento.",
    },
    form: simple({ extraTitle: "Serviço", showAddress: true }),
  },
  textura: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Textura", unit: "m²" },
      { name: "Grafiato", unit: "m²" },
      { name: "Chapisco", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  arquiteto: {
    title: "Novo orçamento",
    publicTitle: "Proposta",
    units: ["projeto", "m²", "etapa", "serviço"],
    defaultUnit: "projeto",
    extras: [],
    suggestions: [
      { name: "Projeto arquitetônico", unit: "projeto" },
      { name: "Projeto de interiores", unit: "projeto" },
      { name: "Projeto de reforma", unit: "projeto" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      itemDeadline: true,
    }),
  },
  "assistencia-tecnica": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "peça"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Diagnóstico", unit: "serviço" },
      { name: "Manutenção", unit: "serviço" },
      { name: "Troca de peça", unit: "peça" },
    ],
    photos: {
      ...photosOptional,
      hint: "Opcional — foto do defeito ou do equipamento.",
    },
    form: simple({
      extraTitle: "Atendimento",
      itemMaterial: true,
    }),
  },
  automacao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Automação de iluminação", unit: "ponto" },
      { name: "Automação de portão", unit: "serviço" },
      { name: "Casa inteligente", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({ extraTitle: "Serviço", showAddress: true }),
  },
  azulejista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Assentamento de porcelanato", unit: "m²" },
      { name: "Assentamento de cerâmica", unit: "m²" },
      { name: "Revestimento de parede", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  calceteiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Calçamento", unit: "m²" },
      { name: "Piso intertravado", unit: "m²" },
      { name: "Assentamento de pedras", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  carpinteiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["peça", "m²", "m", "serviço"],
    defaultUnit: "peça",
    extras: [],
    suggestions: [
      { name: "Estrutura de telhado", unit: "serviço" },
      { name: "Pergolado", unit: "peça" },
      { name: "Porta de madeira", unit: "peça" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      itemNameLabel: "Serviço / peça",
      itemMeasures: true,
      itemPhotoHint: true,
    }),
  },
  chaveiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "cópia"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Abertura de porta", unit: "serviço" },
      { name: "Troca de fechadura", unit: "serviço" },
      { name: "Cópia de chave", unit: "cópia" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      itemPhotoHint: true,
    }),
  },
  concretagem: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m³", "m²", "metro", "unidade", "serviço"],
    defaultUnit: "m³",
    extras: [],
    suggestions: [
      { name: "Laje", unit: "m³" },
      { name: "Calçada", unit: "m²" },
      { name: "Fundação", unit: "m³" },
      { name: "Concreto", unit: "m³" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemAreaNote: true,
      itemPhotoHint: true,
    }),
  },
  construtora: {
    title: "Novo orçamento",
    publicTitle: "Proposta da obra",
    units: ["serviço", "m²", "m³", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Fundação", unit: "serviço" },
      { name: "Alvenaria", unit: "m²" },
      { name: "Estrutura", unit: "serviço" },
      { name: "Acabamento", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  decorador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ambiente", "h"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Decoração de ambiente", unit: "ambiente" },
      { name: "Consultoria", unit: "h" },
      { name: "Produção de ambiente", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      showValidity: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  dedetizador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "m²", "ambiente", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Dedetização", unit: "serviço" },
      { name: "Desratização", unit: "serviço" },
      { name: "Descupinização", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressRequired: true,
      showValidity: false,
      showPrazo: false,
      itemAreaM2: true,
      itemPhotoHint: true,
    }),
  },
  demolicao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "m³", "metro", "unidade", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Demolição de parede", unit: "m²" },
      { name: "Demolição de piso", unit: "m²" },
      { name: "Demolição completa", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do local antes da demolição ajuda o cliente a aprovar.",
    },
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemAreaNote: true,
      itemPhotoHint: true,
    }),
  },
  desentupidor: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Desentupimento de pia", unit: "serviço" },
      { name: "Desentupimento de vaso", unit: "serviço" },
      { name: "Desentupimento de tubulação", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  designer: {
    title: "Novo orçamento",
    publicTitle: "Proposta",
    units: ["serviço", "arte", "peça", "projeto", "pacote"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Logo", unit: "arte" },
      { name: "Identidade visual", unit: "projeto" },
      { name: "Arte para redes sociais", unit: "arte" },
    ],
    photos: photosOptional,
    form: simple({
      showValidity: false,
      showPrazo: false,
      itemDeadline: true,
      itemPhotoHint: true,
    }),
  },
  interiores: {
    title: "Novo orçamento",
    publicTitle: "Proposta",
    units: ["serviço", "projeto", "ambiente", "m²", "produto", "h"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Projeto de interiores", unit: "projeto" },
      { name: "Consultoria", unit: "h" },
      { name: "Projeto de ambiente", unit: "ambiente" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemAreaM2: true,
      itemDeadline: true,
      itemPhotoHint: true,
    }),
  },
  diarista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["diária", "serviço", "ambiente"],
    defaultUnit: "diária",
    extras: [],
    suggestions: [
      { name: "Limpeza padrão", unit: "diária" },
      { name: "Limpeza pesada", unit: "diária" },
      { name: "Limpeza de apartamento", unit: "diária" },
    ],
    photos: { ...photosOptional, enabled: false },
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
    }),
  },
  eletricista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto", "metro"],
    defaultUnit: "ponto",
    extras: [],
    suggestions: [
      { name: "Instalação de tomada", unit: "ponto" },
      { name: "Instalação de iluminação", unit: "ponto" },
      { name: "Instalação de quadro", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  empreiteira: {
    title: "Novo orçamento",
    publicTitle: "Proposta da obra",
    units: ["serviço", "m²", "m³", "diária", "metro", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Alvenaria", unit: "m²" },
      { name: "Reforma", unit: "serviço" },
      { name: "Acabamento", unit: "serviço" },
      { name: "Mão de obra", unit: "diária" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  encanador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto", "metro"],
    defaultUnit: "ponto",
    extras: [],
    suggestions: [
      { name: "Instalação hidráulica", unit: "serviço" },
      { name: "Troca de tubulação", unit: "metro" },
      { name: "Reparo de vazamento", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  "energia-solar": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["sistema", "kWp", "painel", "unidade", "serviço"],
    defaultUnit: "sistema",
    extras: [],
    suggestions: [
      { name: "Sistema fotovoltaico", unit: "sistema" },
      { name: "Instalação", unit: "serviço" },
      { name: "Manutenção", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Instalação",
      showAddress: true,
      showValidity: false,
      itemNameLabel: "Serviço / equipamento",
      itemPowerKwp: true,
      itemPhotoHint: true,
    }),
  },
  "engenheiro-civil": {
    title: "Novo orçamento",
    publicTitle: "Proposta",
    units: ["projeto", "m²", "serviço", "laudo", "ART"],
    defaultUnit: "projeto",
    extras: [],
    suggestions: [
      { name: "Projeto estrutural", unit: "projeto" },
      { name: "Projeto de fundação", unit: "projeto" },
      { name: "Laudo técnico", unit: "laudo" },
      { name: "ART", unit: "ART" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemDeadline: true,
      itemPhotoHint: true,
    }),
  },
  "equipe-obra": {
    title: "Novo orçamento",
    publicTitle: "Orçamento da obra",
    units: ["diária", "serviço", "m²", "m³", "metro", "unidade"],
    defaultUnit: "diária",
    extras: [],
    suggestions: [
      { name: "Mão de obra", unit: "diária" },
      { name: "Reforma", unit: "serviço" },
      { name: "Alvenaria", unit: "m²" },
      { name: "Acabamento", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  esquadrias: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["unidade", "m²", "metro"],
    defaultUnit: "unidade",
    extras: [],
    suggestions: [
      { name: "Janela de alumínio", unit: "unidade" },
      { name: "Porta de alumínio", unit: "unidade" },
      { name: "Esquadria de PVC", unit: "unidade" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Produto / serviço",
      itemSizeWH: true,
      itemPhotoHint: true,
    }),
  },
  eventos: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["evento", "pessoa", "diária", "pacote", "unidade"],
    defaultUnit: "pacote",
    extras: ["eventDate"],
    suggestions: [
      { name: "Buffet", unit: "pessoa" },
      { name: "Decoração", unit: "evento" },
      { name: "Cerimonial", unit: "evento" },
      { name: "Estrutura", unit: "diária" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Evento",
      showAddress: true,
      addressLabel: "Local do evento",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  fossa: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "m³", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Limpeza de fossa", unit: "serviço" },
      { name: "Instalação de fossa", unit: "serviço" },
      { name: "Sumidouro", unit: "unidade" },
      { name: "Manutenção", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemVolumeM3: true,
      itemPhotoHint: true,
    }),
  },
  fotografo: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["ensaio", "evento", "hora", "pacote", "diária"],
    defaultUnit: "pacote",
    extras: ["eventDate"],
    suggestions: [
      { name: "Ensaio fotográfico", unit: "ensaio" },
      { name: "Cobertura de evento", unit: "evento" },
      { name: "Ensaio externo", unit: "ensaio" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto de referência ou do local ajuda o cliente a fechar.",
    },
    form: simple({
      extraTitle: "Ensaio / Evento",
      showAddress: true,
      addressLabel: "Local",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / pacote",
      itemDeadline: true,
      itemDeadlineLabel: "Prazo de entrega (opcional)",
      itemPhotoHint: true,
    }),
  },
  funileiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "peça", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment"],
    suggestions: [
      { name: "Funilaria", unit: "serviço" },
      { name: "Martelinho de ouro", unit: "serviço" },
      { name: "Reparo de para-choque", unit: "peça" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do dano e do reparo ajuda o cliente a aprovar.",
    },
    form: simple({
      extraTitle: "Veículo",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  gas: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "ponto", "metro", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação de gás", unit: "serviço" },
      { name: "Instalação de fogão", unit: "unidade" },
      { name: "Instalação de aquecedor", unit: "unidade" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  gesseiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "unidade", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Forro de gesso", unit: "m²" },
      { name: "Sanca", unit: "metro" },
      { name: "Parede de drywall", unit: "m²" },
      { name: "Moldura", unit: "metro" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  higienizacao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["peça", "lugar", "unidade", "serviço"],
    defaultUnit: "peça",
    extras: [],
    suggestions: [
      { name: "Higienização de sofá", unit: "lugar" },
      { name: "Higienização de colchão", unit: "peça" },
      { name: "Higienização de banco", unit: "peça" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do estofado ajuda a mostrar o estado antes e depois.",
    },
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  impermeabilizador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "unidade", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Impermeabilização de laje", unit: "m²" },
      { name: "Impermeabilização de parede", unit: "m²" },
      { name: "Manta", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  instalador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto", "hora"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação de equipamento", unit: "unidade" },
      { name: "Instalação de móvel", unit: "unidade" },
      { name: "Instalação geral", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  irrigacao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["ponto", "metro", "m²", "unidade", "serviço"],
    defaultUnit: "ponto",
    extras: [],
    suggestions: [
      { name: "Instalação de irrigação", unit: "serviço" },
      { name: "Irrigação por gotejamento", unit: "metro" },
      { name: "Irrigação por aspersão", unit: "ponto" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  isolamento: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "unidade", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Isolamento térmico", unit: "m²" },
      { name: "Isolamento acústico", unit: "m²" },
      { name: "Isolamento de parede", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  jardineiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["diária", "serviço", "m²", "unidade", "visita"],
    defaultUnit: "visita",
    extras: [],
    suggestions: [
      { name: "Manutenção de jardim", unit: "visita" },
      { name: "Poda", unit: "serviço" },
      { name: "Corte de grama", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  limpeza: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["diária", "serviço", "ambiente", "m²", "visita"],
    defaultUnit: "diária",
    extras: [],
    suggestions: [
      { name: "Limpeza residencial", unit: "diária" },
      { name: "Limpeza comercial", unit: "diária" },
      { name: "Limpeza pesada", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  "limpeza-pos-obra": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "diária", "serviço", "ambiente"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Limpeza pós-obra", unit: "m²" },
      { name: "Limpeza pesada", unit: "serviço" },
      { name: "Limpeza de entrega", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  borracharia: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "pneu", "jogo"],
    defaultUnit: "serviço",
    extras: ["equipment"],
    suggestions: [
      { name: "Conserto de pneu", unit: "pneu" },
      { name: "Troca de pneu", unit: "pneu" },
      { name: "Balanceamento", unit: "jogo" },
      { name: "Alinhamento", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do pneu ou do dano ajuda o cliente a aprovar.",
    },
    form: simple({
      extraTitle: "Veículo",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  manutencao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "hora", "diária", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Pequenos reparos", unit: "serviço" },
      { name: "Manutenção geral", unit: "serviço" },
      { name: "Reparos diversos", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  "manutencao-predial": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "hora", "diária", "unidade", "m²", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Manutenção elétrica", unit: "serviço" },
      { name: "Manutenção hidráulica", unit: "serviço" },
      { name: "Pintura", unit: "m²" },
      { name: "Reparos", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço do prédio",
      showValidity: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  marceneiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["unidade", "m²", "metro", "projeto", "serviço"],
    defaultUnit: "unidade",
    extras: [],
    suggestions: [
      { name: "Armário sob medida", unit: "unidade" },
      { name: "Cozinha planejada", unit: "projeto" },
      { name: "Painel", unit: "unidade" },
      { name: "Porta", unit: "unidade" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço",
      showValidity: false,
      itemNameLabel: "Produto / serviço",
      itemMeasures: true,
      itemPhotoHint: true,
    }),
  },
  "marido-de-aluguel": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "hora", "diária", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação", unit: "serviço" },
      { name: "Reparo", unit: "serviço" },
      { name: "Montagem", unit: "serviço" },
      { name: "Pequeno reparo", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  marmorista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["unidade", "m²", "metro", "serviço"],
    defaultUnit: "unidade",
    extras: [],
    suggestions: [
      { name: "Pia de granito", unit: "unidade" },
      { name: "Bancada", unit: "unidade" },
      { name: "Soleira", unit: "metro" },
      { name: "Nicho", unit: "unidade" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemNameLabel: "Produto / serviço",
      itemSizeLW: true,
      itemPhotoHint: true,
    }),
  },
  mecanico: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "peça", "hora", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment", "year", "mileage"],
    suggestions: [
      { name: "Troca de óleo", unit: "serviço" },
      { name: "Freios", unit: "serviço" },
      { name: "Suspensão", unit: "serviço" },
      { name: "Diagnóstico", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do veículo ou da peça ajuda o cliente a aprovar.",
    },
    form: simple({
      extraTitle: "Veículo",
      extraEquipmentLabel: "Marca / modelo",
      showValidity: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  "mestre-de-obras": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "m²", "m³", "diária", "hora", "unidade"],
    defaultUnit: "serviço",
    extras: ["city"],
    suggestions: [
      { name: "Mão de obra", unit: "diária" },
      { name: "Alvenaria", unit: "m²" },
      { name: "Reboco", unit: "m²" },
      { name: "Laje", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  "montador-de-moveis": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "hora", "ambiente"],
    defaultUnit: "serviço",
    extras: ["travelFee"],
    suggestions: [
      { name: "Montagem de guarda-roupa", unit: "serviço" },
      { name: "Montagem de cozinha", unit: "serviço" },
      { name: "Montagem de cama", unit: "serviço" },
      { name: "Desmontagem", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do móvel (opcional) — anexa depois de salvar.",
    },
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da montagem",
      showValidity: false,
      showPrazo: false,
      showTravelFee: true,
      itemNameLabel: "Serviço / móvel",
      itemPhotoHint: true,
    }),
  },
  "moveis-planejados": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["unidade", "m²", "metro", "ambiente", "projeto", "serviço"],
    defaultUnit: "unidade",
    extras: [],
    suggestions: [
      { name: "Armário", unit: "unidade" },
      { name: "Guarda-roupa", unit: "unidade" },
      { name: "Painel", unit: "unidade" },
      { name: "Bancada", unit: "unidade" },
    ],
    photos: photosOptional,
    groupSectionTitle: "Ambientes",
    groupLabel: "Ambiente",
    groupPlaceholder: "Cozinha, quarto…",
    groupSuggestions: ["Cozinha", "Quarto", "Sala", "Banheiro", "Escritório", "Outro"],
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      addressLabel: "Endereço da instalação",
      showValidity: false,
      hideGroups: false,
      catalogTitle: "Serviços / produtos salvos",
      itemNameLabel: "Móvel / ambiente",
      itemSizeWHD: true,
      itemMaterial: true,
      itemMaterialLabel: "Material / acabamento (opcional)",
      itemPhotoHint: true,
    }),
  },
  mudancas: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "viagem", "hora", "diária", "unidade"],
    defaultUnit: "serviço",
    extras: ["destAddress", "eventDate", "access", "elevator"],
    suggestions: [
      { name: "Mudança residencial", unit: "serviço" },
      { name: "Mudança comercial", unit: "serviço" },
      { name: "Carreto", unit: "viagem" },
      { name: "Montagem / desmontagem", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Mudança",
      showAddress: true,
      addressLabel: "Endereço de origem",
      extraEventDateLabel: "Data da mudança (opcional)",
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  outro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "hora", "diária"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Serviço", unit: "serviço" },
      { name: "Visita", unit: "serviço" },
      { name: "Mão de obra", unit: "hora" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  paisagista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["projeto", "m²", "serviço", "unidade"],
    defaultUnit: "projeto",
    extras: [],
    suggestions: [
      { name: "Projeto paisagístico", unit: "projeto" },
      { name: "Jardinagem", unit: "m²" },
      { name: "Plantio", unit: "serviço" },
      { name: "Manutenção", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Projeto",
      showAddress: true,
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  "papel-de-parede": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "rolo", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Papel de parede", unit: "m²" },
      { name: "Adesivo", unit: "m²" },
      { name: "Remoção", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  pavimentacao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Calçada", unit: "m²" },
      { name: "Asfalto", unit: "m²" },
      { name: "Bloco intertravado", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  pedreiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "m²", "diária", "hora", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Alvenaria", unit: "m²" },
      { name: "Reboco", unit: "m²" },
      { name: "Reforma", unit: "serviço" },
      { name: "Contrapiso", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemNameLabel: "Serviço / material",
      itemPhotoHint: true,
    }),
  },
  "personal-organizer": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "ambiente", "hora", "diária"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Organização de armário", unit: "serviço" },
      { name: "Organização de closet", unit: "ambiente" },
      { name: "Organização de mudança", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  pintor: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "serviço", "parede"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Pintura interna", unit: "m²" },
      { name: "Pintura externa", unit: "m²" },
      { name: "Pintura de teto", unit: "m²" },
      { name: "Massa corrida", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  "pintor-automotivo": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "peça", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment"],
    suggestions: [
      { name: "Pintura", unit: "serviço" },
      { name: "Retoque", unit: "peça" },
      { name: "Polimento", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto da peça ou do dano ajuda o cliente a aprovar.",
    },
    form: simple({
      extraTitle: "Veículo",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  piscineiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["visita", "serviço", "diária", "unidade"],
    defaultUnit: "visita",
    extras: [],
    suggestions: [
      { name: "Limpeza de piscina", unit: "visita" },
      { name: "Tratamento da água", unit: "visita" },
      { name: "Manutenção", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  "piso-laminado": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Piso laminado", unit: "m²" },
      { name: "Piso vinílico", unit: "m²" },
      { name: "Rodapé", unit: "metro" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  "poco-artesiano": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "metro", "unidade"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Perfuração", unit: "metro" },
      { name: "Manutenção", unit: "serviço" },
      { name: "Limpeza de poço", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemPhotoHint: true,
    }),
  },
  "polimento-pisos": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Polimento", unit: "m²" },
      { name: "Cristalização", unit: "m²" },
      { name: "Restauração de piso", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  "portao-automatico": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "ponto"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação de motor", unit: "unidade" },
      { name: "Manutenção de portão", unit: "serviço" },
      { name: "Automação de portão", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  "redes-protecao": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Rede de janela", unit: "m²" },
      { name: "Rede de sacada", unit: "m²" },
      { name: "Rede de piscina", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  redes: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "ponto", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Instalação de Wi-Fi", unit: "serviço" },
      { name: "Cabeamento", unit: "metro" },
      { name: "Ponto de rede", unit: "ponto" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemPhotoHint: true,
    }),
  },
  refrigeracao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "peça"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Manutenção de câmara fria", unit: "serviço" },
      { name: "Conserto de freezer", unit: "serviço" },
      { name: "Troca de peça", unit: "peça" },
    ],
    photos: {
      ...photosOptional,
      hint: "Opcional — foto do equipamento ou do defeito.",
    },
    form: simple({
      extraTitle: "Atendimento",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemMaterial: true,
      itemPhotoHint: true,
    }),
  },
  "seguranca-eletronica": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "ponto", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Câmera / CFTV", unit: "ponto" },
      { name: "Alarme", unit: "serviço" },
      { name: "Interfone", unit: "unidade" },
      { name: "Cerca elétrica", unit: "metro" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  serralheiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["unidade", "m²", "metro", "serviço"],
    defaultUnit: "unidade",
    extras: [],
    suggestions: [
      { name: "Portão", unit: "unidade" },
      { name: "Grade", unit: "unidade" },
      { name: "Estrutura metálica", unit: "serviço" },
      { name: "Corrimão", unit: "metro" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemNameLabel: "Produto / serviço",
      itemSizeWH: true,
      itemPhotoHint: true,
    }),
  },
  "social-media": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["pacote", "arte", "serviço", "h"],
    defaultUnit: "pacote",
    extras: [],
    suggestions: [
      { name: "Gestão de redes", unit: "pacote" },
      { name: "Artes para Instagram", unit: "arte" },
      { name: "Pacote mensal", unit: "pacote" },
    ],
    photos: photosOptional,
    form: simple({
      showValidity: false,
      showPrazo: false,
      itemDeadline: true,
      itemPhotoHint: true,
    }),
  },
  soldador: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "hora", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Solda", unit: "serviço" },
      { name: "Reparo", unit: "serviço" },
      { name: "Estrutura", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  sonorizacao: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["evento", "diária", "serviço", "hora"],
    defaultUnit: "evento",
    extras: ["eventDate"],
    suggestions: [
      { name: "Som", unit: "evento" },
      { name: "Palco", unit: "diária" },
      { name: "DJ", unit: "evento" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Evento",
      showAddress: true,
      addressLabel: "Local do evento",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / equipamento",
      itemPhotoHint: true,
    }),
  },
  tapeceiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade", "metro"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Estofamento de sofá", unit: "serviço" },
      { name: "Cadeira", unit: "unidade" },
      { name: "Cabeceira", unit: "unidade" },
    ],
    photos: {
      ...photosOptional,
      hint: "Foto do móvel ajuda a mostrar o estado e o tecido.",
    },
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  "ar-condicionado": {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Instalação de split", unit: "unidade" },
      { name: "Limpeza", unit: "unidade" },
      { name: "Manutenção", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Atendimento",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / produto",
      itemPhotoHint: true,
    }),
  },
  celular: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "peça", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Troca de tela", unit: "serviço" },
      { name: "Troca de bateria", unit: "serviço" },
      { name: "Conector / carga", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Opcional — foto do aparelho ou do defeito.",
    },
    form: simple({
      extraTitle: "Atendimento",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemMaterial: true,
      itemPhotoHint: true,
    }),
  },
  eletrodomesticos: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "peça", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Conserto de geladeira", unit: "serviço" },
      { name: "Máquina de lavar", unit: "serviço" },
      { name: "Fogão", unit: "serviço" },
    ],
    photos: {
      ...photosOptional,
      hint: "Opcional — foto do aparelho ou do defeito.",
    },
    form: simple({
      extraTitle: "Atendimento",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemMaterial: true,
      itemPhotoHint: true,
    }),
  },
  informatica: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "hora", "unidade"],
    defaultUnit: "serviço",
    extras: ["equipment", "brand", "model"],
    suggestions: [
      { name: "Formatação", unit: "serviço" },
      { name: "Upgrade", unit: "serviço" },
      { name: "Visita técnica", unit: "hora" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Atendimento",
      showAddress: true,
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / peça",
      itemPhotoHint: true,
    }),
  },
  telhadista: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "metro", "serviço", "unidade"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Telhado", unit: "m²" },
      { name: "Calha", unit: "metro" },
      { name: "Manutenção", unit: "serviço" },
      { name: "Troca de telha", unit: "unidade" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  terraplanagem: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m³", "m²", "hora", "serviço"],
    defaultUnit: "m³",
    extras: [],
    suggestions: [
      { name: "Terraplanagem", unit: "m³" },
      { name: "Aterro", unit: "m³" },
      { name: "Escavação", unit: "hora" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Obra",
      showAddress: true,
      addressLabel: "Endereço da obra",
      showValidity: false,
      itemVolumeM3: true,
      itemPhotoHint: true,
    }),
  },
  toldos: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "unidade", "metro", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Toldo", unit: "m²" },
      { name: "Cobertura", unit: "m²" },
      { name: "Policarbonato", unit: "m²" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemLayout: "area-m2",
      itemPhotoHint: true,
    }),
  },
  topografo: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["serviço", "laudo", "hectare", "m²"],
    defaultUnit: "serviço",
    extras: [],
    suggestions: [
      { name: "Levantamento topográfico", unit: "serviço" },
      { name: "Georreferenciamento", unit: "serviço" },
      { name: "Planta", unit: "serviço" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemDeadline: true,
      itemPhotoHint: true,
    }),
  },
  videomaker: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["evento", "pacote", "hora", "diária"],
    defaultUnit: "pacote",
    extras: ["eventDate"],
    suggestions: [
      { name: "Filme de evento", unit: "evento" },
      { name: "Vídeo institucional", unit: "pacote" },
      { name: "Cobertura", unit: "diária" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Ensaio / Evento",
      showAddress: true,
      addressLabel: "Local",
      showValidity: false,
      showPrazo: false,
      itemNameLabel: "Serviço / pacote",
      itemDeadline: true,
      itemDeadlineLabel: "Prazo de entrega (opcional)",
      itemPhotoHint: true,
    }),
  },
  vidraceiro: {
    title: "Novo orçamento",
    publicTitle: "Orçamento",
    units: ["m²", "unidade", "metro", "serviço"],
    defaultUnit: "m²",
    extras: [],
    suggestions: [
      { name: "Box", unit: "unidade" },
      { name: "Janela de vidro", unit: "unidade" },
      { name: "Espelho", unit: "m²" },
      { name: "Guarda-corpo", unit: "metro" },
    ],
    photos: photosOptional,
    form: simple({
      extraTitle: "Serviço",
      showAddress: true,
      showValidity: false,
      itemNameLabel: "Produto / serviço",
      itemSizeWH: true,
      itemPhotoHint: true,
    }),
  },
};
